name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        preset: [debug, release]

        config:
          - { os: ubuntu-latest, c_compiler: gcc, cpp_compiler: g++ }
          - { os: ubuntu-latest, c_compiler: clang, cpp_compiler: clang++ }
          - { os: windows-latest, c_compiler: cl, cpp_compiler: cl }

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set compiler environment variables
      shell: bash
      run: |
        echo "CC=${{ matrix.config.c_compiler }}" >> $GITHUB_ENV
        echo "CXX=${{ matrix.config.cpp_compiler }}" >> $GITHUB_ENV

    - name: Configure CMake using preset
      run: cmake --preset ${{ matrix.preset }}

    - name: Build project
      run: cmake --build --preset ${{ matrix.preset }}

    - name: Run tests
      if: matrix.preset == 'debug'
      working-directory: build/${{ matrix.preset }}
      run: ctest -C debug --output-on-failure
